site_name: Playcount 2003
copyright: Copyright &copy; 2024 marc2003
strict: true
theme:
  name: material
  features:
    - content.code.copy
    - navigation.sections
markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: "#"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marc2k3
extra_css:
  - stylesheets/extra.css

