name: build
on:
  push:
    paths:
      - '**'
      - '!docs/**'
      - '!mkdocs.yml'
jobs:
  build:
    name: ${{ matrix.project }}
    runs-on: windows-2022

    strategy:
      matrix:
        project: [foo_playcount_2003]

    steps:
    - name: Clone repo
      run: |
        git clone ${{ github.server_url }}/${{ github.repository }}

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Set up vcpkg
      run: |
        vcpkg integrate install
        vcpkg install nlohmann-json wtl --triplet x86-windows
        vcpkg install nlohmann-json wtl --triplet x64-windows

    - name: Create component folder
      run: |
        mkdir component
        mkdir component\x64

    - name: Build Win32
      working-directory: ${{ matrix.project }}
      run: |
        msbuild vc17\${{ matrix.project }}.sln -m -p:Platform=Win32 -p:Configuration=Release
        copy vc17\Win32\Release\${{ matrix.project }}.dll ..\component
        copy vc17\Win32\Release\${{ matrix.project }}.pdb ..\component
        git clean -fdx && git submodule foreach --recursive git clean -fdx

    - name: Build x64
      working-directory: ${{ matrix.project }}
      run: |
        msbuild vc17\${{ matrix.project }}.sln -m -p:Platform=x64 -p:Configuration=Release
        copy vc17\x64\Release\${{ matrix.project }}.dll ..\component\x64
        copy vc17\x64\Release\${{ matrix.project }}.pdb ..\component\x64

    - name: Upload with pdb
      if: startsWith(github.ref, 'refs/tags')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}-${{ github.ref_name }}-with-pdb
        path: component

    - name: Delete pdb files and zip for release
      if: startsWith(github.ref, 'refs/tags')
      working-directory: component
      run: |
        del ${{ matrix.project }}.pdb
        del x64\${{ matrix.project }}.pdb
        7z a -tzip ${{ matrix.project }}-${{ github.ref_name }}.fb2k-component *

    - name: Release
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      with:
        files: component/${{ matrix.project }}-${{ github.ref_name }}.fb2k-component
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
